- name: create a vm
  register: myserver
  nova_compute:
    state: present
    auth_url: "{{os_auth_url}}"
    login_username: "{{os_username}}"
    login_password: "{{os_password}}"
    login_tenant_name: "{{os_tenant_name}}"
    name: larstest
    image_id: "{{os_image_id}}"
    key_name: "{{os_key_name}}"
    wait_for: 200
    flavor_id: "{{os_flavor_id}}"
    nics:
      - net-id: "{{os_network_id}}"
    user_data: |
      #!/bin/sh
      
      date > /root/flagfile
    auto_floating_ip: true

# Yikes! It looks like nova_compute returns different information
# depending on whether or not the server existed, so we need two
# different plays for registerting the ip address.

- name: add host to inventory
  add_host:
    hostname: "{{myserver.info.name}}"
    ansible_ssh_host: "{{myserver.public_ip}}"
    ansible_ssh_user: fedora
    groups: openstack_nodes
  when: myserver|changed

- name: add host to inventory
  add_host:
    hostname: "{{myserver.info.name}}"
    ansible_ssh_host: "{{myserver.public_ip.0}}"
    ansible_ssh_user: fedora
    groups: openstack_nodes
  when: not myserver|changed

