- name: launch a nova instance
  hosts: localhost
  roles:
   - openstack_instances

- hosts: openstack_nodes
  gather_facts: false
  tasks:
    - name: wait for remote node to boot
      wait_for: 
        host: "{{ansible_ssh_host}}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost

- hosts: openstack_nodes
  sudo: true
  tasks:
    - yum:
        name: "{{item}}"
        state: latest
      with_items:
        - git
        - screen
        - tcpdump
