- name: launch a nova instance
  hosts: localhost
  roles:
    - role: openstack_instances
      os_flavor_id: 2
      os_host_name: myhost1
    - role: openstack_instances
      os_flavor_id: 3
      os_host_name: myhost2

- hosts: openstack_nodes
  gather_facts: false
  tasks:
    - name: wait for remote node to boot
      wait_for: 
        host: "{{ansible_ssh_host}}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost

- hosts: openstack_nodes
  sudo: true
  tasks:
    - command: dnf -y install {{item}}
      with_items:
        - git
        - screen
        - tcpdump
